build: remove ansi flag
Was causing the following build error and is unncessary

/home/matt/Projects/jhbuild/native/usr/include/glib-2.0/glib/gtypes.h:417:8:
error: unknown type name ‘inline’