Workaround issue with the RPiCam and resolutions higher than 720p.
 * When the RPi is configured with a resolution higher than 720p like 1080p,
   and some application requests OWRTC a full-screen video the requested
   source video resolution on the RPiCam can cause firmware fatal errors.

 * This happens with WebKit on AppRTC with the RPi configured on a 1080p
   display:

     mmal: mmal_vc_port_enable: failed to enable port vc.ril.video_encode:in:0(OPQV): EINVAL
     mmal: mmal_port_enable: failed to enable connected port (vc.ril.video_encode:in:0(OPQV))0x59c350 (EINVAL)
     mmal: mmal_connection_enable: output port couldn't be enabled
     ==== Error message start ====
     Error in element video-source.
     Error: Internal data flow error.
     Debugging info: gstbasesrc.c(2948): gst_base_src_loop ():
     /GstPipeline:local-video-capture-source-bin-0/GstRpiCamSrc:video-source: streaming task paused, reason error (-5)

 * With this patch, AppRTC works fine on a 1080p screen with the RPiCam.
   The following GStreamer logs happen:

    DEBUG [...] RPiCam: Asked source video resolution of 2160x1080
    WARN  [...] RPiCam: The asked source video resolution was capped to 1440x720 to void mmal firmware related errors